"""add clinical metadata columns to items

Revision ID: 65aad24d4996
Revises: a1b2c3d4e5f6
Create Date: 2026-02-28 16:44:25.971326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65aad24d4996'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_ar', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('clinical_use', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('clinical_category', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('specialty_tags', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('item_family_group', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('detailed_use', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_items_category_ar'), 'items', ['category_ar'], unique=False)
    op.create_index(op.f('ix_items_clinical_category'), 'items', ['clinical_category'], unique=False)
    op.create_index(op.f('ix_items_clinical_use'), 'items', ['clinical_use'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_item_family_group'), 'items', ['item_family_group'], unique=False)
    op.create_index(op.f('ix_items_specialty_tags'), 'items', ['specialty_tags'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_specialty_tags'), table_name='items')
    op.drop_index(op.f('ix_items_item_family_group'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_clinical_use'), table_name='items')
    op.drop_index(op.f('ix_items_clinical_category'), table_name='items')
    op.drop_index(op.f('ix_items_category_ar'), table_name='items')
    op.drop_column('items', 'detailed_use')
    op.drop_column('items', 'item_family_group')
    op.drop_column('items', 'specialty_tags')
    op.drop_column('items', 'clinical_category')
    op.drop_column('items', 'clinical_use')
    op.drop_column('items', 'category_ar')
    # ### end Alembic commands ###
