"""add max limit tables

Revision ID: 7b7b97a458d3
Revises: 20250228000000
Create Date: 2026-02-28 14:39:39.863483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7b97a458d3'
down_revision: Union[str, None] = '20250228000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('department_max_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=False),
    sa.Column('effective_year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'department_id', 'effective_year', name='uq_department_max_limits_item_dept_year')
    )
    op.create_index(op.f('ix_department_max_limits_department_id'), 'department_max_limits', ['department_id'], unique=False)
    op.create_index('ix_department_max_limits_dept_item', 'department_max_limits', ['department_id', 'item_id'], unique=False)
    op.create_index(op.f('ix_department_max_limits_id'), 'department_max_limits', ['id'], unique=False)
    op.create_index(op.f('ix_department_max_limits_item_id'), 'department_max_limits', ['item_id'], unique=False)
    op.create_table('facility_max_limits',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('total_max_quantity', sa.Integer(), nullable=False),
    sa.Column('effective_year', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility_max_limits')
    op.drop_index(op.f('ix_department_max_limits_item_id'), table_name='department_max_limits')
    op.drop_index(op.f('ix_department_max_limits_id'), table_name='department_max_limits')
    op.drop_index('ix_department_max_limits_dept_item', table_name='department_max_limits')
    op.drop_index(op.f('ix_department_max_limits_department_id'), table_name='department_max_limits')
    op.drop_table('department_max_limits')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
